use_text_title: false
# title: de;code
use_logo: true
logo: assets/images/de;code.png
favicon: assets/images/de;code.gif
author: Perplexeus
email: me@perplexeus.com
description: > # this means to ignore newlines until "baseurl:"
  Building awesome satisfying code.

theme: jekyll-theme-minimal

# social links
twitter_username: heyPerplexeus # DO NOT include the @ character, or else the build will fail!
github_username:  MePerplexeus # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
