title: The Code
author: Perplexeus
email: me@perplexeus.com
description: > # this means to ignore newlines until "baseurl:"
  Building awesome satisfying code.

theme: jekyll-theme-minimal

# social links
twitter_username: heyPerplexeus # DO NOT include the @ character, or else the build will fail!
github_username:  Perplexeus # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
