#title: "/assets/images/de;code.png"
#title: de;code
use_logo: true
# logo image to use. logo images are constrained at 50px in height.
logo: assets/images/de;code.png
author: Perplexeus
email: me@perplexeus.com
description: > # this means to ignore newlines until "baseurl:"
  Building awesome satisfying code.

theme: jekyll-theme-minimal

# social links
twitter_username: heyPerplexeus # DO NOT include the @ character, or else the build will fail!
github_username:  MePerplexeus # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
